### ISSUE TITLE
Feat song bug

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/munity#11]
When a song has someone else featured, the song is marked as wrong even if it is right.
maybe split the song before and after the feat, if it has feat in it and the part of the list with the index 0 is the song name (remember about the brackets)

**Comment by DillonB07** [comment]
I could have a go at removing any brackets and dashes from the songs. For brackets it would remove the brackets and contents. For a dash it would remove everything after the dash as well as the dash.

This could cause a few issues, but should work for the majority of songs?

**Comment by VulcanWM** [comment]
> I could have a go at removing any brackets and dashes from the songs. For brackets it would remove the brackets and contents. For a dash it would remove everything after the dash as well as the dash.
> 
> This could cause a few issues, but should work for the majority of songs?

Is it worth causing issue for some songs and it working for the rest of the songs?

**Comment by DillonB07** [comment]
Possibly not, but I think it would help more songs than it would break/stop working
