### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by VulcanWM** [VulcanWM/munity#3]
Add some more information to the main page and then add that in the `README.md` file.

**Comment by VulcanWM** [comment]
> I saw your comment on Replverse. I'm not amazing at logos, but I can give it a go.
> 
> What sort of logo do you want? _Decided to post here incase of the data losses/rollbacks_

@DillonB07 Thanks for agreeing to help
I was hoping for a simplistic design but something that is eye catching. And if it could be dark mode that would be even better.

**Comment by VulcanWM** [comment]
@DillonB07 woah that's amazing, the Spotify logo isn't really needed and V1 is better

**Comment by DillonB07** [comment]
Here's my File sharing app.
Sign in with Replit and you can download a zip file containing, png, jpg, gif, ico and a surprise. *The surprise probably won't be useful but it was fun to make*

https://file-sharing.dillonb07.repl.co

*Styling will come at some point. I'm aware it's extremely ugly.*

**Comment by DillonB07** [comment]
No problem.

Just a link to either my [GitHub](https://github.com/DillonB07) or [portfolio](https://dillonb07.is-a.dev) will be good.
Feel free to ask me for anything else code or design related!

**Comment by VulcanWM** [comment]
you're amazing! this is so good! thank you so much for your help
i added your portfolio to it :)
